# Generated by Django 2.1 on 2018-10-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Raza'),
        ),
    ]
